
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 100
  profiles:
    active: local

logging:
  level:
    org.hibernate.SQL: debug

server:
  tomcat:
    max-http-form-post-size: 5MB